### ISSUE TITLE
Special chars in windows blender.exe path

### ISSUE THREAD

**Issue by Vinc3r** [armadillica/flamenco-manager#5]
(Tested on win 10 64b)
It seems that _\\_ and _space_ char are not allowed when setting blender.exe path in the manager.

Example : _C:\\Program Files\\Blender Foundation\\blender-2.78-windows64\\_ will not work ; worker console say that it can't find blender in _C:\\Program_.
By testing a portable version in _C:/temp/blenderportable/_, worker find blender.exe.

**Comment by sybrenstuvel** [comment]
- Spaces are supported, but need surrounding quotes. The variables can also contain CLI arguments for Blender, so there needs to be a distinction between "the command" and its arguments. Using `"C:\Program Files\Blender Foundation\blender-2.78-windows64\blender.exe" --enable-new-depsgraph` should work just fine.
- Backslashes need to be doubled, because single backslashes work as escape characters. For example, `\n` is a newline. `C:\\temp\\blenderportable\\blender.exe` should work too.

I'll include this in the documentation, and close this issue once that's done. If it turns out not to work for you, feel free to re-open this issue and give me more context (like exact Manager configuration and Worker logs).
